[project]
name = "studybooktdd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.3",
    "pytest>=8.4.1",
    "selenium>=4.33.0",
    "webdriver-manager>=4.0.2",
]
